services:
  backend:
    image: "gcr.io/wasmer/wapm-backend:${BACKEND_IMAGE_TAG:-latest}"
    command: ["bash", "./docker-entrypoint.sh"]
    env_file:
      - backend/env
    volumes:
      - "./backend/backend_fixtures.json:/data/fixtures.json"
      - "./backend/db.sqlite3:/app/db.sqlite3"
      - "./backend/backend_entrypoint.sh:/app/docker-entrypoint.sh"
    ports:
      - "8080:8080"
    environment:
      - "DJANGO_LOG_LEVEL=INFO"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
      start_period: 3m

  celery:
    image: "gcr.io/wasmer/wapm-backend:${BACKEND_IMAGE_TAG:-latest}"
    command: ["bash", "./celery-entrypoint.sh"]
    env_file:
      - backend/env
    volumes:
      - "./backend/db.sqlite3:/app/db.sqlite3"
      - "./backend/celery_entrypoint.sh:/app/celery-entrypoint.sh"
    environment:
      - "DJANGO_LOG_LEVEL=INFO"

  redis:
    image: "redis:alpine"

  edge:
    depends_on:
      backend:
        condition: service_healthy
    privileged: true
    network_mode: host
    image: gcr.io/wasmer/edge:latest
    command: ["wasmer-server", "serve", "-c", "/app/platform_config.yaml", "--ssh-port", "9022"] # ssh port change is needed because github runners have port 22 allocated
    volumes:
      - "./edge/platform_config_local.yaml:/app/platform_config.yaml"
    devices:
      - "/dev/net/tun"
    cap_add:
      - "SYS_PTRACE"
      - "SYS_NICE"
      - "NET_ADMIN"
      - "NET_RAW"
      - "NET_BIND_SERVICE"
    environment:
      RUST_LOG: "wasmer_server=trace,wasmer_wasix=trace"
      RUST_BACKTRACE: "full"
