 # NOTE: Add static local webc packages that you want test below.
static_webc:
  #- full_name: "wasmer/wasmer-sh"
  #  version: 0.2.6
  #  path: "/prog/webc/wasmer-sh-0.2.6-0bda6ea5-3f24-4cd1-a0d6-3c387b78dd70.webc"
  #- full_name: "wasmer/wasmer-io"
  #  version: 0.15.1
  #  path: "/prog/webc/wasmer-io-0.15.1-502cb4c5-42b6-4def-89fe-a50199f7726a.webc"
  #- full_name: "wasmer/static-web-server"
  #  version: 1.0.4
  #  path: "/prog/webc/static-web-server-1.0.4-67c57d3a-5f9f-456e-914e-81505595de3a.webc"
  #- full_name: "wasmer/static-web-server"
  #  version: 1.0.4
  #  path: "/prog/webc/static-web-server-async-1.0.2-a34ef1c2-99f2-49c4-965f-02b5e2ce61a8.webc"
  #- full_name: "wasmer/static-web-server-async"
  #  version: 1.0.2
  #  path: "/prog/webc/static-web-server-async-1.0.2-a34ef1c2-99f2-49c4-965f-02b5e2ce61a8.webc"

package_registries:
  - url: https://wapm.io
    api_endpoint: http://backend:8080/graphql
    auth_token: null
    is_default: true

module_cache:
  # s3:
  #   endpoint: http://localhost:9000
  #   bucket: "deploy"
  #   access_key_id: "minioadmin"
  #   secret_access_key: "minioadmin"

auto_hostnames:
  - hostname: .app.wapm.dev
    registry: https://wapm.io
    runner: WCgi
  - hostname: .proxy.wapm.dev
    registry: https://wapm.io
    runner: WebProxy
  - hostname: .ws.wapm.dev
    registry: https://wapm.dev
    runner: TcpProxy

runtime:
  min_blocking_thread_count: 4
  max_blocking_thread_count: 500
  default_thread_parallelism: 2

geo_tls: 120

gateway:
  limits:
    concurrency: 1000
    request_timeout_secs: 180
    cname_recursive_limit: 5
    max_backlog: 500
  acme:
    enabled: true
    # prod: https://acme-v02.api.letsencrypt.org/directory
    # test: https://acme-staging-v02.api.letsencrypt.org/directory
    # Local ACME Pebble server - https://github.com/letsencrypt/pebble
    url: https://localhost:14000/dir
    # storage:
    #   path_fallback: data/tls
  deployment_domains:
    - domain: wasmer.app
      registry: http://backend:8080/graphql
      admin_auth_token: "wap_default_token"
    - domain: wasmer.dev
      registry: http://backend:8080/graphql
      admin_auth_token: "wap_default_token"

geolite_token: "PUT_TOKEN_HERE"
master_network_key: "PUT_KEY_HERE"

recursive_dns_server: 8.8.8.8
recursive_dns_cache_max: 10000
host_resolver_cache_duration_success: 180sec
host_resolver_cache_duration_failed: 10sec

socket:
  timeout_secs: 50
  # as the keep alive is greater than the timeout this will mean the sockets
  # will automatically close after ten seconds of idle time
  keep_alive_secs: 40
  overlay_mtu: 1400
  # the maximum number of seconds to keep an idle instance running
  # after scaling out. this represents the time it takes to scale
  # back down to one instance
  reuse_instance_ttl_secs: 15
  # the amount of time to keep the last instance active before its shutdown
  # which will cause everything including its module to be unloaded. higher
  # values here will reduce latency but increase memory pressure
  reuse_last_instance_ttl_secs: 300
  # connections are reused when calling instances with a maximum pool
  # size that prevents them from being overloaded excessively
  reuse_instance_socket_pool_size: 128
  # number of connections to reusable instances before they start scaling
  # out to multiple instances per node. this number should be the optimal
  # connection count for best latest
  reuse_instance_scale_out_threshold: 96
  # maximum number of permits to an instance before it starts throttling. this
  # number should be the maximum connections before degradation in performance
  # starts to kick in
  reuse_instance_max_permits_per_instance: 128
  # maximum number of reusable instances per node. this number should be
  # an upper bound on density
  reuse_instance_max_instances_per_node: 3
  # timeout when the instance has never been connected to before
  proxy_connect_init_timeout_secs: 15
  # timeout after the instance has successfully had a connection in the past
  proxy_connect_nominal_timeout_secs: 5
  # number of attempts to make connection attempts before another
  # reusable instance is attempted
  proxy_connect_retries: 3
  proxy_send_timeout_secs: 8
  proxy_recv_timeout_secs: 10
  # Tainting will automatically shutdown instances if connection attempts
  # fail to the instance
  enable_tainting: true

dns_server:
  storage:
    # path_fallback: data/dns_store

metering:
  publish_interval: 15s
  # prometheus_remote_write_url: "https://wasmer-dev2:aoriep7eep6phienohTh@metering-promscale.internal.wapm.dev/write"
  # clickhouse:
  #   url: http://localhost:8123
  #   database: default


api:
  http_port: 9050
  grpc_port: 9051
  gateway_hostname: node-api.internal.wasmer.app

observability:

instance_logging:
  default_capabilities:
    enabled: true
    capture_stderr: true

token_public_keys:
  - |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAspxdvSTXT5/VmcYD7pbL
    5TEf7CNbSjNQZ89brwJFTbRsNs4yzLJsxjYmF4rMZkTHlFGULnJKB3JUTJ3wrHWD
    HQUu8DijLGuUe3SBiQShfWtUGNbHoF+1UB2zn3xRC8oWe5+gXhdHZZDKJFSKwrWY
    O2TezXhhu2IWtRBANqrgX87q4DCs6ufv6ILB9TLVI0K2uVWGpykxE4xFN0ZzSqIs
    b2ggoFSqjvPh5YsGjzL79CQvvPJdiEL0enQ8FlRy9pOva5zOYWeyjYTlkfcnU+D2
    Bs4rwUEsUKLKhqvycGkWKtT4n1u8n6/OGVP21b+9x9zYZqtTVdPrl6fNGuCgv2Bw
    BMU+9jc2F3XHPL2KaBsRtTrXWIVtNvB7SOHE81l6Tyfs6CtZUBdXwXuCU0MHZaNy
    dXYyo5m/0FrUSwuKCD+dxdeLgT0wGtJOHoj0Duck8mt7YvXKWGfHajs3x1AGLbFo
    UdpMdhcu44i42oaX5jfT7dqG9eivNyQBQZyZPvGhhDcv5K7/GVl8P7NZfZyNWSd/
    2NvQqmr7FsYovWkea9fRBdMwI8WYzjS6gPtI33UzyD17oyGbEOAHlITjnkWZG5zd
    ci61tMpnTn4/0+vf0eHeHVJrDUO5EdbgggOs+Gx4X7xl9OVmPeVwOQRqj6HUrWDh
    abd8qckaHZ+xuJa+PDGiuEkCAwEAAQ==
    -----END PUBLIC KEY-----
  - |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
    4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u
    +qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyeh
    kd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ
    0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdg
    cKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbc
    mwIDAQAB
    -----END PUBLIC KEY-----

static_domains:
-
  domain: "localhost"
  registry: https://wasmer.io
  namespace: wasmer
  package: python-sh
  runner: WebProxy

cluster:
  regions:
  -
    identifier: "local"
    region_index: 0
    description: "devserver"
    nodes:
    - description: "devserver-1"
      node_index: 0
      global_ip4: 0.0.0.0
      internal_ip4: 0.0.0.0
      active: true
