name: "Run tests with new tests pushed on main branch"
'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: push-to-main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmerio/setup-wasmer@v2
      - name: Cargo Registry Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/advisory-db
            ~/.cargo/git
            ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo target cache
        uses: actions/cache@v3
        with:
          path: |
            target/
          key: cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          wasmer config set registry.url https://registry.wasmer.io/graphql
          wasmer login ${{ secrets.WAPM_PROD_TOKEN }}
          wasmer config set registry.url https://registry.wasmer.wtf/graphql
          wasmer login ${{ secrets.WAPM_DEV_TOKEN }}
          cargo test --no-fail-fast
        env:
          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
          MYSQL_DBNAME: ${{ vars.MYSQL_DBNAME }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
          MYSQL_CERT: ${{ secrets.MYSQL_CERT }}
          PG_HOST: ${{ vars.PG_HOST }}
          PG_DBNAME: ${{ vars.PG_DBNAME }}
          PG_USERNAME: ${{ secrets.PG_USERNAME }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ vars.PG_PORT }}
