name: "Run tests with new tests pushed on main branch"
'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: push-to-main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmerio/setup-wasmer@v2
      - uses: denoland/setup-deno@v1
      - name: test
        env:
          WASMER_REGISTRY: https://registry.wasmer.wtf/graphql
          WASMER_TOKEN: ${{ secrets.WAPM_DEV_TOKEN }}
        run: deno test --allow-all --parallel
      - name: notify failure in slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Integration tests failed ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' https://hooks.slack.com/services/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
